name: Docs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-26

    steps:
    - uses: actions/checkout@v4

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5

    - name: Build Docs
      id: docs
      run: |
        OUT_DIR="$RUNNER_TEMP/docs"
        mkdir -p "$OUT_DIR" && \
        swift package \
        --allow-writing-to-directory "$OUT_DIR" \
        generate-documentation \
        --target RBDB \
        --target Datalog \
        --enable-experimental-combined-documentation \
        --disable-indexing \
        --transform-for-static-hosting \
        --hosting-base-path "${{ steps.pages.outputs.base_path }}" \
        --output-path "$OUT_DIR" && \
        echo "out_dir=$OUT_DIR" >> "$GITHUB_OUTPUT"

    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v4
      with:
        path: ${{ steps.docs.outputs.out_dir }}

  deploy:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
